### ISSUE TITLE
对象属性能否直接获取

### ISSUE THREAD

**Issue by ZhangBohan** [leancloud/python-sdk#105]
```
from leancloud import Query
query = Query(GameScore)
game_score = query.get('520ca0bbe4b07e8e0e847e31')
# print game_score.get('playerName')
print game_score.playerName
```

可否支持通过重写`__getattr__`达到获取参数名称时无需使用`get`方法

例如：
```
def __getattr__(self, attr):
    return self.get(attr)
```

**Comment by aisk** [comment]
支持的，不过需要注意别和现有的变量名冲突就好。

**Comment by ZhangBohan** [comment]
@aisk 支持是指现在就可以用？还是说SDK下版会支持？还是说我每个都要自己写一下这段代码？

**Comment by aisk** [comment]
@ZhangBohan 需要自己实现。

SDK 不准备支持这种用法，潜在风险比较大。准备支持类似这样的写法：

```python
from leancloud import Object
from leancloud import field
class Foo(Object):
    bar = field.Text(max_length=100)
    baz = field.Number(required=True)

**Comment by ZhangBohan** [comment]
@aisk 哦，收到。那像你说的这种类型打算在哪版支持？

**Comment by aisk** [comment]
@ZhangBohan 还没有排期……其实实现很快的，主要是要考虑 API 设计是否合适。另外你也可以自己尝试实现，很简单的。

**Comment by ZhangBohan** [comment]
@aisk 恩，难肯定不难，回头我看看

**Comment by aisk** [comment]
@ZhangBohan thx~ 用的爽的话欢迎发 PR！

**Comment by yongbo** [comment]
def __getattr__(self, key):
     
    if self.attributes.has_key(key):
        return self.attributes.get(key)
    else:
        raise AttributeError

import leancloud

setattr(leancloud.Object, '__getattr__', __getattr__)

临时用的话，在不修改leancloud 代码的时候，可以自己加一段这个。 我测试都正常，

**Comment by aisk** [comment]
@yongbo :+1:
