### ISSUE TITLE
缺少 fetch_all API

### ISSUE THREAD

**Issue by aisk** [leancloud/python-sdk#129]

**Comment by hjiang** [comment]
还缺少 `insert_all` 和 `delete_all`.

**Comment by aisk** [comment]
@hjiang fetch_all 这个操作 API Server 没有批量请求的接口，看了下 Android 内部实现，也是在每个对象上调用 fetch 操作的。这样的话感觉不适合暴露给用户，以免用户错误估计了这个调用的时间复杂度。用户手动进行遍历调用的话在 Python 里也是很简单的。
