### ISSUE TITLE
几次遇到TypeError: XXX is not JSON serializable的问题

### ISSUE THREAD

**Issue by nightfade** [leancloud/python-sdk#132]
之前用engine.current_user的时候就遇到这个问题，后来绕过去了。现在在云函数里返回一个Object的子类又遇到了。追了一下leanengine.py里的`dispatch_request`方法里的`return Response(json.dumps(result), mimetype='application/json')`，result是一个包含Object对象的字典，Python的LeanEngine返回值不能是对象吗？

Traceback (most recent call last):
INFO 2015-12-27 00:54:21   File "/mnt/avos/data/uluru-cloud-code/repos/a06snenjxu3v9ohetuhedb0dfjmw81ejxoqz9cnuetewzy2m/lib/python2.7/site-packages/leancloud/engine/leanengine.py", line 104, in dispatch_request
INFO 2015-12-27 00:54:21     return Response(json.dumps(result), mimetype='application/json')
INFO 2015-12-27 00:54:21   File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
INFO 2015-12-27 00:54:21     return _default_encoder.encode(obj)
INFO 2015-12-27 00:54:21   File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
INFO 2015-12-27 00:54:21     chunks = self.iterencode(o, _one_shot=True)
INFO 2015-12-27 00:54:21   File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
INFO 2015-12-27 00:54:21     return _iterencode(o, 0)
INFO 2015-12-27 00:54:21   File "/usr/lib/python2.7/json/encoder.py", line 184, in default
INFO 2015-12-27 00:54:21     raise TypeError(repr(o) + " is not JSON serializable")
INFO 2015-12-27 00:54:21 TypeError: <leancloud.object_.YMAVAccess object at 0x7f1e0402e610> is not JSON serializable

**Comment by aisk** [comment]
您好，暂时还不可以，后续会增加一个新的接口，来允许返回 leancloud.Object 对象。

**Comment by nightfade** [comment]
谢谢~  那如果直接return obj.dump()，是不是在客户端SDK是可以自动解析成相应对象的？

**Comment by aisk** [comment]
@nightfade 您好，不推荐这么用。

**Comment by nightfade** [comment]
了解了，多谢！
