### ISSUE TITLE
update 支持 where 条件

### ISSUE THREAD

**Issue by aisk** [leancloud/python-sdk#136]

**Comment by Panmax** [comment]
求抓紧实现~

**Comment by aisk** [comment]
@Panmax 收到，争取这周末或者下周实现。

**Comment by Panmax** [comment]
请问这个完成了吗？

**Comment by aisk** [comment]
@Panmax 还没有

**Comment by Panmax** [comment]
跳票好严重😂

**Comment by Panmax** [comment]
我改怎么操作来使用这个新特性？升级python sdk吗？

**Comment by aisk** [comment]
@Panmax 这个版本还没有发布，稍等 review 没有问题了就可以发布了。之后就可以升级 SDK 来使用。

**Comment by Panmax** [comment]
@aisk 好的，等SDK可以更新的时候，方便通知我一下吗？

**Comment by aisk** [comment]
@Panmax 已发布。

**Comment by Panmax** [comment]
@aisk 👍

**Comment by Panmax** [comment]
@aisk 最新的sdk是1.4.0吗？

**Comment by aisk** [comment]
@Panmax 是 1.4.1，如果用的是第三方 pypi 源的话可能是源没有及时同步，可以换官方源试试。
