### ISSUE TITLE
文件上传没有直接通过七牛的接口上传

### ISSUE THREAD

**Issue by aisk** [leancloud/python-sdk#16]
目前是通过 LeanCloud 的服务器中转一次的，对文件大小有限制，需要改为直接通过七牛的 SDK 上传。

**Comment by jwfing** [comment]
js sdk 是否也有这个问题？ @wangxiao @sunchanglong 如果有，也需要一并改掉。不论大小，先传到我们服务器就是挺浪费带宽的一件事情。

**Comment by aisk** [comment]
@jwfing JS SDK 已经直接使用七牛的 SDK 了。

**Comment by killme2008** [comment]
在前端环境下仍然是走我们服务器的， node.js 是走七牛。
