### ISSUE TITLE
errors with python 3.4

### ISSUE THREAD

**Issue by adamin1990** [leancloud/python-sdk#164]
i am using python 3.4.3,and when i input these code and run it,it print these errors:
`AttributeError: 'dict' object has no attribute 'iteritems'`
mycode
```python
import leancloud
from leancloud import Object
from leancloud import LeanCloudError
leancloud.init("","")
TestObject= Object.extend('TestObject')
test_object = TestObject()
test_object.set('foo', 'bar')
try:
    test_object.save()
except LeanCloudError:
    print("出错了")
```

**Comment by lord63** [comment]
@adamin1990 Hi, thanks for the report! The 3.x support for the python SDK is still under development, so there may be some bugs.
By the way, could you please paste the full error log here, it'll help us locate the problem.

**Comment by DionysusG** [comment]
We are now fully supporting Python 3, you can update your python SDK to the newest version to avoid the problem.
