### ISSUE TITLE
部分用户遇到上传文件损坏问题

### ISSUE THREAD

**Issue by aisk** [leancloud/python-sdk#167]
相关论坛讨论： https://forum.leancloud.cn/t/python/5686/5

**Comment by DionysusG** [comment]
在 Windows 7下实验了，最新版本的 Python 2.7 File().read() 可以正常输出 2 Mb 的文件。同时，Python 的文档表示 File().read() 所调用的 sys.stdin.read() 在默认情况下是阻塞 (blocking) 而非非阻塞（non-blocking) 的。

**Comment by aisk** [comment]
嗯，看来不是这个问题引起的。

**Comment by aisk** [comment]
长期未能复现。
