### ISSUE TITLE
How can I get a user's roles?

### ISSUE THREAD

**Issue by JokerQyou** [leancloud/python-sdk#178]
I did not find any method to get all roles (objects or strings) of a user who is logged in.
I did a little search and reached [here](https://ticket.leancloud.cn/tickets/3443), which said LeanCloud is going to add a `User.getRole` method for doing this.
Did this method actually get added in the Javascript SDK?
If so, I think there should be an equivalent in the Python SDK; If not, is it still recommended to follow the solution in that ticket?

Thanks.

**Comment by aisk** [comment]
HI @JokerQyou sorry for reply late. you can use `leancloud.Relation.reverse_query` to get the user's roles like this:

```python
leancloud.Relation.reverse_query('_Role', 'users', u).find()
```

We will add a method as a shortcut for this.

**Comment by JokerQyou** [comment]
Thank you for your reply!
However it's been too long since I opened this issue, and I have already forgot what the context was...
Also it seems like you're using Lean ticket for ticket management but did not import all the old tickets, so the link in my initial comment is no longer available...
