### ISSUE TITLE
leancloud.Object.get 增加默认值

### ISSUE THREAD

**Issue by aisk** [leancloud/python-sdk#189]
方法签名：

`leancloud.Object.get(key, default=None)`

如果传了 default，如果 get 结果为 None，则自动返回 default 值。

**Comment by aisk** [comment]
@tang3w 好像 SDK 的 API 修改需要找你确认一下，能否增加这个默认值？这个和 Python 常见行为以及内置的 dict 类型的行为一致的，希望可以增加。

**Comment by tang3w** [comment]
支持。但要注意一下 Python 不同版本对默认值参数的处理逻辑是否是一致的，会不会引起 API 不兼容的问题？

**Comment by aisk** [comment]
一致的，没有问题，那就开始实施吧 @DionysusG

**Comment by DionysusG** [comment]
def5944

**Comment by DionysusG** [comment]
def594460c47d10430a49242af1ba3ca958a9ee1

**Comment by DionysusG** [comment]
implemented at def594460c47d10430a49242af1ba3ca958a9ee1
