### ISSUE TITLE
说明依赖的 requests 版本号

### ISSUE THREAD

**Issue by killme2008** [leancloud/python-sdk#19]

**Comment by aisk** [comment]
这个上周已经增加了

**Comment by killme2008** [comment]
没有在文档里看到。

**Comment by aisk** [comment]
是在 setup.py 里面指定了 requests 的版本号，用户安装的时候应该会指定安装这个版本的 requests。

但是刚才测了一下，在 Ubuntu 环境下直接用 pip install leancloud-sdk 的方式安装 SDK，如果系统之前用 apt-get install python-requests（apt-get 里的版本是2.2，缺少一些我们 SDK 里用到的功能），会导致系统有两个 requests，并且 apt-get 的在前面。

我修改一下 SDK，在 2.2 里面也能运行。
