### ISSUE TITLE
处理 Hook 请求时校验签名

### ISSUE THREAD

**Issue by jysperm** [leancloud/python-sdk#194]
需要校验的请求：

* before 和 after 类 Hook
* 用户相关 Hook：onVerified、onLogin
* 离线分析完成：BigQueryJobComplete
* 实时通讯 Hook（实际是以云函数实现的），具体列表见 https://leancloud.cn/docs/realtime_v2.html#云引擎_Hook

签名算法见 https://github.com/leancloud/uluru-platform/issues/2242
Node SDK 相关 PR https://github.com/leancloud/leanengine-node-sdk/pull/73
请先等待命令行工具的支持发布（否则就无法在本地调试 Hook 了，预计这两天就发布） https://github.com/leancloud/avoscloud-code-command/pull/150
需要等待实时通讯后端的修改上线 https://github.com/leancloud/avoscloud-push/issues/903

**Comment by aisk** [comment]
https://github.com/leancloud/python-sdk/pull/220
