### ISSUE TITLE
 可否为 Object 序列化时添加两个字段

### ISSUE THREAD

**Issue by wuyazi** [leancloud/python-sdk#196]
leancloud/object_.py:180
```
        if self.created_at is not None:
            obj['createdAt'] = self.created_at.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
        if self.updated_at is not None:
            obj['updatedAt'] = self.updated_at.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
```
另外可否在序列化时添加自定义字段

**Comment by aisk** [comment]
这两条会在服务器自动创建，不需要添加。

`序列化时添加自定义字段` 的具体需求时什么，是需要自动填充字段吗？这样推荐在控制台使用默认值功能比较合适。

**Comment by wuyazi** [comment]
我是在云引擎中用到了，后端取得数据然后序列化，返回给前端。
前端取得的数据没法获取到 createdAt 和 updatedAt。
具体需求：一个论坛类网站，前端需要显示帖子的创建时间和更新时间。

**Comment by aisk** [comment]
后端是指 Python 开发的云引擎应用？请直接使用 obj.created_at 和 obj.updated_at 访问这两个字段。

**Comment by wuyazi** [comment]
我知道这样可以访问到，但是感觉不友好，我认为这两个字段是本来就该带的
```
item = obj.dump()
item["createdAt"] = obj.created_at
item["updatedAt"] = obj.updated_at
return jsonify(item)
```
有点啰嗦，感觉在 dump 序列化的时候直接加上这两个字段比较好。
```
return jsonify(obj.dump())
```

**Comment by aisk** [comment]
如果是前后端沟通的话，可以考虑在前端引用 js sdk，这样就可以直接传递一个 leancloud.Object 对象到前端，更加方便一些。

如果前端因为静态文件体积等原因不能饮用 js sdk，那最好自己写一个函数来做这件事情。
