### ISSUE TITLE
美国区节点上传文件走统一接口

### ISSUE THREAD

**Issue by aisk** [leancloud/python-sdk#197]
目前是根据`是否为美国区`来判断使用哪个接口进行上传，现在需要改为走统一的 filetokens 接口。

ref: https://github.com/leancloud/paas/issues/835

**Comment by jwfing** [comment]
为了增加紧迫感，我加上了 bug 标签。

**Comment by DionysusG** [comment]
为了增加紧迫感，我 PR 了

**Comment by DionysusG** [comment]
Implemented at #201
