### ISSUE TITLE
leancloud.File 支持 io.StringIO

### ISSUE THREAD

**Issue by aisk** [leancloud/python-sdk#203]
目前 Python2.7 的 `io.StringIO` 实例不能拿来做 `leancloud.File` 构造函数的参数。

**Comment by DionysusG** [comment]
我们是假设 Python 2 不会传 unicode 的文件么？测了下目前 cStringIO 不能存 ASC2 range 外的 code. 如果让 io.StringIO 和 cStringIO 一致的话转换一下就好了，但 io.StringIO 是能存 unicode 的，转换的时候可能会出问题。

**Comment by aisk** [comment]
好像看来并不能支持
