### ISSUE TITLE
支持 leancloud.Engine#register

### ISSUE THREAD

**Issue by aisk** [leancloud/python-sdk#241]
~~Node ／ PHP 直接在 SDK 中提供了此实例，并且作为一个全局变量提供给用户，免去用户实例化的麻烦。~~

~~Python SDK 之前需要用户自己初始化，导致很多不必要的麻烦，可以考虑改掉。~~

---

ref: https://github.com/leancloud/python-sdk/issues/241#issuecomment-252413920

**Comment by jysperm** [comment]
我觉得没什么必要，用户想要全局变量的话自己用语言提供的机制去做就好了。之前 JS SDK 和 Node SDK 还在讨论如何去掉全局的实例呢。

**Comment by aisk** [comment]
@jysperm 之前也这么觉得的，但是后来发现这个全局实例并没有引入过麻烦。反而需要用户初始化倒引入了一些麻烦：

- 有些用户尝试在每个文件都初始化 leanengine.Engine，而这么使用会出现问题。
- 如果想要把云函数写在多个文件时，如果有对 Python 模块加载机制不熟的用户，很容易引发循环引用，或者其中一个文件没有被加载的情况。如果有个全局实例的话，只需要用户记住一点「在入口文件 import 所有的云函数文件」即可。

**Comment by jysperm** [comment]
这样的话我觉得可以在示例项目里实现这个全局实例，不需要改 SDK 本身。

**Comment by aisk** [comment]
还有一个问题，现在的 leancloud.Engine 是个 WSGI middleware，导致用户实际使用的时候项目会变成这样：

- app.py 文件中，初始化自己的 WSGI 函数（比如 flask）
- cloud.py 文件中，从 app.py import WSGI 函数，以此初始化 leancloud.Engine，得到 engine 这个实例
- (假如需要将云函数写到多个文件) foo.py 中，从 cloud.py 引入 engine，并且调用 engine.define
- wsgi.py 文件（也是入口文件）中，从 cloud.py 引入 engine 变量。

这样整个流程比较复杂，并且项目文件组织不当的话容易引入循环引用。并且对 WSGI 没有概念的使用者，不太好理解这个流程。

-----------

不过我又思考了一下，最早 leancloud.Engine 是参考 flask 来设计的，flask 最早也有这个问题。但是 flask 引入了 BluePrint 来解决这个问题：可以在其他文件实例化一个 BluePrint，然后在统一的文件中引入这些 BluePrint，然后注册到全局的 app.py 上。

我们也可以参考这个方案：

foo.py:

```python
engine = leancloud.Engine()  # 类似 BluePrint 的用法

@engine.define
def foo():
    pass
```

cloud.py:

```python
import foo

engine = leancloud.Engine()  # 全局使用的 engine 实例

engine.register(foo.engine)
```

wsgi.py:

```python
from cloud import engine
from app import my_wsgi_func

application = engine.wrap(my_wsgi_func)
```

这样代码依赖顺序就从 

app -> cloud -> wsgi

变成了

```
app -> wsgi
cloud -> wsgi

**Comment by dlmyb** [comment]
现在 2.0 怎么样了。。

**Comment by aisk** [comment]
@dlmyb 可以参考 `next` 分支。
