### ISSUE TITLE
Failed to upload the zip file

### ISSUE THREAD

**Issue by Objc0** [leancloud/python-sdk#272]
code：
```
with open(fileName, 'rb') as fData:
	fwFile = leancloud.File(fileName, fData)
	fwFile.save()
	fwFile.fetch()
```

ErrorMsg: 
```
File "...python3.5/site-packages/leancloud/file_.py", line 209, in save
        self._save_to_qiniu(content['token'], content['key'])
File "...python3.5/site-packages/leancloud/file_.py", line 158, in _save_to_qiniu
        raise LeanCloudError(1, 'the file is not saved, qiniu status code: {0}'.format(info.status_code))
```

leancloud.errors.LeanCloudError: LeanCloudError: [1] the file is not saved, qiniu status code: -1

xx.zip >20 MB but I can upload pictures. iOS and Android is OK.

**Comment by aisk** [comment]
Dose it got the same error when you retried it?

**Comment by Objc0** [comment]
YES，Every time. Two files are not the same size, large file can not be uploaded, small one is OK.

**Comment by aisk** [comment]
Hello, I tried a 40M file with the same code, and got it passed.

Can you check your qiniu SDK's version using command: `pip freeze` ?

**Comment by Objc0** [comment]
leancloud-sdk==1.6.5
qiniu==7.0.9.1
Need to upgrade？I will try again after upgrade.

**Comment by aisk** [comment]
It's weird. Can you give me your app id / key via  this email: lan@leancloud.rocks and let me try this codes with it?

**Comment by Objc0** [comment]
Using python3.5 will trigger this problem. The problem may be caused by qiniu. Thank you for your help @aisk

**Comment by aisk** [comment]
duplicated: https://github.com/leancloud/python-sdk/issues/274
