### ISSUE TITLE
v2.0.0 还无法使用？设置依赖版本为v2.0.0的时候提示最新是1.3版本

### ISSUE THREAD

**Issue by BadReese** [leancloud/python-sdk#339]

**Comment by aisk** [comment]
发现有些用户在 requirements.txt 里没有指定 SDK 依赖范围，所以没太敢贸然发布。目前发布在 `leancloud` 这个模块上了。

**Comment by BadReese** [comment]
那我想用应该怎么写requirements.txt呢？好像部署的时候选择下载最新依赖也是无法下下来的 @aisk

**Comment by BadReese** [comment]
因为刚好2.0的版本的fetch可以选择include其他字段下来，所以我才着急更新

**Comment by BadReese** [comment]
我该怎么使用2.0版本呢请问？ @aisk

**Comment by aisk** [comment]
直接在 requirements.txt 里删掉 leancloud-sdk 的依赖，然后改成 `leancloud` 就可以。另外最好在其中也明确写上 SDK 的版本，至少写明 `leancloud>=2.0.0,<3.0.0`。

**Comment by BadReese** [comment]
好的 谢谢 @aisk

**Comment by BadReese** [comment]
怎么连leancloud<3.0.0,>=2.0.0也不行了。。
贴下错误日志
`部署失败：The command '/bin/sh -c pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple' returned a non-zero code: 1:
Collecting leancloud<3.0.0,>=2.0.0 (from -r requirements.txt (line 1))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement leancloud<3.0.0,>=2.0.0 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for leancloud<3.0.0,>=2.0.0 (from -r requirements.txt (line 1))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning`

 @aisk

**Comment by aisk** [comment]
似乎线上使用的 pypi 源整体挂了，稍等我们正在紧急修复。

**Comment by BadReese** [comment]
我以为改成leancloud-sdk-ng了 @aisk

**Comment by aisk** [comment]
@BadReese leancloud-sdk-ng 并不是 LeanCloud 维护的一个模块，我不确定代码是基于哪个分支的。不过目前看上去换其他模块也无法部署成功，因为 pypi 挂掉了。

**Comment by BadReese** [comment]
@aisk  恩 确实 我刚试了下还是无法部署成功

**Comment by aisk** [comment]
@BadReese 现在应该可以了，刚才线上使用的清华的 pypi 源，但是从早晨开始似乎挂了： https://pypi.tuna.tsinghua.edu.cn/simple/ ，现在紧急切到了其他的源上。

**Comment by BadReese** [comment]
你说之前我也访问过这个源 确实开不了 哈哈 @aisk
