### ISSUE TITLE
relation.query无法指定排序

### ISSUE THREAD

**Issue by BadReese** [leancloud/python-sdk#350]
以前也是无法排序，通过合并一个空查询进去
```reviewSubQuery = cloudTopic.relation(TopicStore.KEY_REVIEWS).query

    emptyReviewSubQuery = Review.query
    emptyReviewSubQuery.does_not_exist(KEY_OBJECT_ID)
    reviewQuery = Review.query.or_(reviewSubQuery, emptyReviewSubQuery)
reviewQuery.descending(KEY_CREATED_AT)
```
就可以正常排序，但是最近发现失效了
是否官方手动修复了这个BUG？
。。

**Comment by BadReese** [comment]
用的是leancloud>=2.0.0,<3.0.0
话说leancloud-sdk那个2.0什么时候上线

**Comment by BadReese** [comment]
@aisk

**Comment by dlmyb** [comment]
尝试一下 `reviewQuery = Review.descending(KEY_CREATE_AT).does_not_exist(KEY_OBJECT_ID)`？

**Comment by BadReese** [comment]
你是指emptyReviewSubQuery = Review.descending(KEY_CREATE_AT).does_not_exist(KEY_OBJECT_ID) 么？

**Comment by aisk** [comment]
这部分似乎没有变动。不合并空查询，直接进行查询会有什么现象？

**Comment by aisk** [comment]
另外 2.0 分支的代码不会发布到 leancloud-sdk 这个模块上了，以后请使用 leancloud 这个模块。

**Comment by BadReese** [comment]
@aisk 这样啊，我后来发现不是排序的问题 你看看

SDK 版本号：leancloud>=2.0.0,<3.0.0

异常调用栈：

topic = TopicStore.Topic.create_without_data("5938179e2f301e005886c024")
topic.fetch()
query = topic.relation(TopicStore.KEY_REVIEWS).query
list = query.find()
return len(list)

我写了个云函数查询该relation的条数，返回的是30
但是用控制台点击relations查看，返回的是49条
为什么会有这种问题？

**Comment by aisk** [comment]
这个问题在工单中有回复，我们继续在工单中沟通吧？

**Comment by BadReese** [comment]
@aisk 
恩 搞定了，确定是count的不准确导致的，实际上数据只剩下30条，感谢你
