### ISSUE TITLE
查询错误：GeoPoint latitude None < -90.0

### ISSUE THREAD

**Issue by BadReese** [leancloud/python-sdk#376]
SDK 版本号：{"version": "2.1.4", "runtime": "cpython-2.7.6"}

异常调用栈：GeoPoint latitude None < -90.0

查询语句：{u'limit': 30, u'include': u'user,attachments,likeReasons,dislikeReasons,poi,movie,irrelevantAttachments,subReviews', u'where': {u'$or': [{u'$relatedTo': {u'object': {u'className': 'Topic', u'__type': u'Pointer', u'objectId': u'594093a3128fe1006a09af6d'}, u'key': u'reviews'}}, {'objectId': {u'$exists': False}}], 'category': {u'$ne': 3}}, u'order': u'-sortedDate'}

很怪，没有GEO的条目会导致查询失败？想不通，我这句语句也没有涉及GEO POINT呀 @Ian

**Comment by aisk** [comment]
我测试了一下查询一个有 GeoPoint，并且值为空的数据，直接查询没有问题。能否在控制台里找一下出错的这条数据，点一下 objectId，把 JSON 结构的数据贴一下？我这里看到的数据，如果有空的话，是没有这个值的，所以没有出错。

**Comment by BadReese** [comment]
@aisk 现在的问题就是我也不知道是哪条出错的，很尴尬

**Comment by BadReese** [comment]
@aisk 有没有什么主意

**Comment by BadReese** [comment]
@aisk 我的APP ID：CNvQ4PuYbgArzonyTXCHrdXm-gzGzoHsz

**Comment by aisk** [comment]
在这行：https://github.com/leancloud/python-sdk/blob/master/leancloud/query.py#L225 的 for 循环里打印一下 result 的值，应该能看出来是哪条出错，直接把出错的数据对应的 result 的内容贴出来就可以。

**Comment by BadReese** [comment]
服务器的SDK我改动会生效么？

**Comment by BadReese** [comment]
部署后不是用的你们的SDK？

**Comment by aisk** [comment]
可以在本地跑一下。本地 `import leancloud; print(leancloud)` 能找到文件的位置。

**Comment by BadReese** [comment]
找到了，那条的经纬度变成了null,null ，，，

**Comment by BadReese** [comment]
为什么能写入这样的数据呢。。

**Comment by BadReese** [comment]
而且这个GEO POINT 无法置None

**Comment by BadReese** [comment]
可以，还好Unset掉了

**Comment by aisk** [comment]
这个不确定了，似乎服务端应该限制一下这类插入的数据 @paomian

**Comment by weakish** [comment]
这个问题和 sdk 关系不大，先关掉了。
