### ISSUE TITLE
文档中的 get_a_conversation 函数找不到？

### ISSUE THREAD

**Issue by da2018** [leancloud/python-sdk#386]
https://leancloud.cn/docs/im-servermgmt-guide-python.html#hash547568837

这里面一大堆函数都不清楚哪里 import 来的？

```
import leancloud

conversation = get_a_conversation()

messages = find_by_conversation(conversation.id)

```

**Comment by da2018** [comment]
find_by_conversation 最起码我能搜到，get_a_conversation 在包里都没有，让用户猜吗？

**Comment by ym** [comment]
get_a_conversation 是一个需要用户自己实现的方法，举个栗子：

```
def get_a_conversation():
  return leancloud.Conversation.query.get(object_id)
```

我们近期会更新一下这个文档。

**Comment by da2018** [comment]
🔫

这种比较初级的 demo 文档应该让用户一下子就能 run 起来才好啊，我看了源码还是一脸懵逼，希望早点补充一下吧。

**Comment by weakish** [comment]
python 服务端即时通讯指南上周已经更新了。
