### ISSUE TITLE
上传文件时的中文问题

### ISSUE THREAD

**Issue by smallevil** [leancloud/python-sdk#395]
f = File.create_with_url('测试', url)
f.save()

这样调用上传后,_File表里的name不是中文,变成了"%E5%8E%BB%E8%A7%81%E4%BD%A0"
但是我用后台你们自己的功能是可以正常显示中文的.
我试了用urllib. quote也不行.

这个要怎么转换?

**Comment by weakish** [comment]
已在 [论坛讨论](https://forum.leancloud.cn/t/topic/20031)
