### ISSUE TITLE
Object.get 方法的一些疑问

### ISSUE THREAD

**Issue by Ma233** [leancloud/python-sdk#416]
当我对获取到的 leancloud 对象调用 get 方法时，如何区分：
* 没有 select 对应字段而导致的值为 None
* 数据库中存储了值 None
* 数据库中未设置对应的值，默认返回 None

btw: 你们 get 方法的默认值参数拼错了 deafult(default)

**Comment by Ma233** [comment]
我这边的应用场景是希望通过一个 leancloud 表中的记录来更新数据库中的记录
```python
    def update_by_leancloud(self, lean_obj, commit=True):
        data = self._extract_data_from_lean_obj(lean_obj, include_oid=False)
        _data = {k: v for k, v in data.items() if v is not None}
        return self.update(**_data, commit_=commit)
```

**Comment by weakish** [comment]
> 当我对获取到的 leancloud 对象调用 get 方法时，如何区分

> 没有 select 对应字段而导致的值为 None
> 数据库中存储了值 None
> 数据库中未设置对应的值，默认返回 None

不区分。建议您数据库中尽量不要存 null 值，如果无数据，那么就不要 set 相应的 key。

> 你们 get 方法的默认值参数拼错了 deafult(default)

感谢报告，因为修正这个会破坏兼容性，需要等下一个大版本才能改了。

**Comment by weakish** [comment]
拼写错误的问题已经在 #417 修复（增加参数的方式保留了兼容性）
