### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by isaced** [leancloud/python-sdk#43]
are there plans to support Python 3?

**Comment by aisk** [comment]
Under planning.

**Comment by lord63** [comment]
@aisk Hi, it seem that I've done the python 3.x port for the SDK(tests passed on 2.7.11 and 3.5.0) in my [fork](https://github.com/lord63-forks/python-sdk/tree/python3-support). Any interests?

**Comment by aisk** [comment]
@lord63 Cool! I think a dev branch is needed, because I think it's good to have some developers who interested with python 3 version SDK to have a test usage before we release it.

And thanks again for the work!

**Comment by aisk** [comment]
@lord63 I have pushed a new branch `python3`, now you can make PR on it.

**Comment by aisk** [comment]
According to @lord63 's help, now our SDK can runs in Python3, any one can try it in python3 branch. And you can add this `git+https://github.com/aisk/leancloud-python-sdk.git@master#egg=leancloud-sdk
` to your `requirements.txt`

The LeanEngine runtime will support Python3 soon.

**Comment by DionysusG** [comment]
Leancloud Python SDK is fully supporting Python 3 now.
