### ISSUE TITLE
依赖库版本过旧

### ISSUE THREAD

**Issue by fanshuai** [leancloud/python-sdk#446]
1.  安装 Werkzeug 1.0.0
> 报：ImportError: cannot import name 'LocalProxy' from 'werkzeug'

2. 其他库，qiniu、requests、urllib3
> ERROR: leancloud 2.5.0 has requirement qiniu<7.2.4,>=7.1.4, but you'll have qiniu 7.2.6 which is incompatible.
> ERROR: leancloud 2.5.0 has requirement requests<=2.22.0,>=2.20.0, but you'll have requests 2.23.0 which is incompatible.
> ERROR: leancloud 2.5.0 has requirement urllib3<=1.25.3,>=1.24.3, but you'll have urllib3 1.25.8 which is incompatible.

是否考虑更新？

**Comment by weakish** [comment]
Werkzeug 的依赖问题已经在 #444 中修复，我们本周会发布新版本。作为临时方案，您可以手动在 requirements.txt 里指定 Werkzeug 版本范围为 `>=0.11.11,<1.0.0`

SDK 依赖和系统已安装的包的依赖冲突建议通过 virtualenv 规避。

后续我们也会更新依赖库，但是目前还没有排期。

**Comment by fanshuai** [comment]
辛苦，已使用pyenv规避依赖包冲突。

其他三个依赖库升级可能没有兼容性问题，只是需要充分测试。

**Comment by weakish** [comment]
2.5.1 昨天已经发布。

**Comment by fanshuai** [comment]
> 1. 安装 Werkzeug 1.0.0
> 
> > 报：ImportError: cannot import name 'LocalProxy' from 'werkzeug'

我这边测试，问题[1]仍存在。

**Comment by weakish** [comment]
能把 requirements.txt 贴一下吗？照理 2.5.1 已经指定了  `Werkzeug<1.0.0`，`Werkzeug` 如果是 1.0.0 的话安装 leancloud 包时应该会报错呀。

**Comment by fanshuai** [comment]
> 能把 requirements.txt 贴一下吗？照理 2.5.1 已经指定了 `Werkzeug<1.0.0`，`Werkzeug` 如果是 1.0.0 的话安装 leancloud 包时应该会报错呀。

我理解错了，没有问题，感谢。
