### ISSUE TITLE
1.2.1版本sdk上传图片异常

### ISSUE THREAD

**Issue by dylanninin** [leancloud/python-sdk#69]
- leancloud-sdk (1.2.1) 上传图片时，异常 http://ac-9zapehri.clouddn.com/V1x7fIuzGqir5SsThqoUyWQUBRlwTSuuF4rBzo07.jpg
-  leancloud-sdk (1.0.15) 同样的方式上传，正常 http://ac-9zapehri.clouddn.com/JbIdGu3kWTGty7TfYeAPJRk4psK1fJOk0mbfajzL.jpg

其他版本的sdk暂未验证过。

**Comment by DionysusG** [comment]
你好，请问能提供下上传图片的相关代码和返回的异常么？

**Comment by dylanninin** [comment]
使用不同版本的SDK运行时，都能正常运行，能够看到打印出来的url（即以上提供的url）
以下是测试的代码：

```python
import leancloud
from leancloud import File
from StringIO import StringIO

leancloud.init('the_app_id', 'the_app_key')

image = open('200.jpg')
f = File('200.jpg', image)
image.close()
f.save()
print f.url

**Comment by sbitpdc** [comment]
返回的信息都正常。

**Comment by DionysusG** [comment]
我们刚发布了1.2.2版本的SDK修复了这个问题

**Comment by sbitpdc** [comment]
Good!害得我们昨晚调试了很久！

**Comment by sam726** [comment]
就是啊，搞到2点多

**Comment by lzjun567** [comment]
老板说了明天不加班

**Comment by sbitpdc** [comment]
7楼是老板

**Comment by dylanninin** [comment]
一个建议，发布的新版本pip leancloud-sdk (1.2.1)能否在版本库里打上对应的tag 1.2.1？

**Comment by aisk** [comment]
@dylanninin 感谢建议，以后都会有 tag 的。
