### ISSUE TITLE
v1.2.2 travis都没有通过啊。  

### ISSUE THREAD

**Issue by bboalimoe** [leancloud/python-sdk#75]

**Comment by aisk** [comment]
是的，之前 travis ci 服务器没有在大陆，导致跑单元测试的时候很多都会 timeout ，所以我们现在没办法保证发布之前 travis 可以跑通。但是肯定会保证本地可以跑通单元测试。

另外我们也会尽快想办法解决这个问题的。

**Comment by aisk** [comment]
现在单元测试改在 us 节点跑了。
