### ISSUE TITLE
User.create_follower_query和User.create_followee_query无法使用

### ISSUE THREAD

**Issue by BlackGlory** [leancloud/python-sdk#81]
调用User.create_follower_query(id).find(), 返回的结果永远是 [].

社区里没有人回复我, 所以我自己看了一下源码, 发现create_follower_query调用的是_User的API, 以至于每次的返回值都是[].

在[https://forum.leancloud.cn/t/python-sdk-create-follower-query/2159](https://forum.leancloud.cn/t/python-sdk-create-follower-query/2159)里有一个较为简陋的临时解决方法.

Lutz在[https://ticket.avosapps.com/tickets/6222](https://ticket.avosapps.com/tickets/6222)也曾提到"通过日志看到，FriendshipQuery最终请求的path是"/1.1/classes/_User"，这个请求path应该是有误吧？"

这个问题似乎在[https://github.com/leancloud/python-sdk/issues/34](https://github.com/leancloud/python-sdk/issues/34)里没有得到解决.

**Comment by DionysusG** [comment]
谢谢你的代码！ 这个 bug 的问题在于我们之前对 friendshipQury 的实现有些问题，我们已经修复，将会在下个版本中放出。

**Comment by aisk** [comment]
https://github.com/leancloud/python-sdk/pull/78

**Comment by aisk** [comment]
已发布 1.2.5，麻烦尝试一下是否修复了这个 bug。

**Comment by BlackGlory** [comment]
已测试, 1.2.5版本可正常使用.
