### ISSUE TITLE
上传文件，metaData 中没有 _checksum 

### ISSUE THREAD

**Issue by lzwjava** [leancloud/python-sdk#85]
当前是：
![c9ks _euh6o unov_qp yp](https://cloud.githubusercontent.com/assets/5022872/9248637/fb4f6938-41ef-11e5-9cf4-35cc27f3885d.jpg)

iOS 上传后，是 

![image](https://cloud.githubusercontent.com/assets/5022872/9248653/2cdc5b5a-41f0-11e5-8382-e130c6dc1cf0.png)

_checksum 就是文件的 md5 值。

测试样例：这个[文件](http://ac-x3o016bx.clouddn.com/zoqkpSHCwdckVDDO6kyFMdC)的 _checksum 是 `f2f24ead97e0bf664193a535d31e6ac3`

@aisk

**Comment by DionysusG** [comment]
话说可以发下你的源码么？

**Comment by lzwjava** [comment]
@DionysusG 是 python sdk 没有算 _checksum

**Comment by aisk** [comment]
@lzwjava 是的，JS SDK 里也没有算。好像不同 SDK 之间 metaData 没有统一。这个哪里有标准？

**Comment by lzwjava** [comment]
@killme2008

**Comment by aisk** [comment]
metaData 规范： https://github.com/leancloud/uluru-platform/wiki/上传文件API文档

**Comment by DionysusG** [comment]
Implemented at #201
