### ISSUE TITLE
user login 以后没有session code？

### ISSUE THREAD

**Issue by zysoo** [leancloud/python-sdk#93]
Doc 中提到
>  login(username=None, password=None)
> 登陆用户。如果用户名和密码正确，服务器会返回用户的 sessionToken 。

但是我login返回为None. 
```python
token = User().login(request.form.get('email'), request.form.get('password'))
```
使用User.get_current()可以得到leancloud user object
使用User().get_session_token()返回也是None
然后我看了一下SDK中login部分：
```python
response = client.post('/login', params=self.dump())
        content = utils.response_to_json(response)
        server_data = self.parse(content, response.status_code)
        self._finish_fetch(server_data, False)
        self._handle_save_result(True)
        if 'smsCode' not in server_data:
            self.attributes.pop('smsCode', None)
```
没有地方设置 _session_token
请问我miss了那里？

**Comment by DionysusG** [comment]
你好，login 方法返回的 session_token 会被保存在 login 的 User 实例中。我们不提供修改 _session_token 的方法。

get_session_token 是实例方法，你可以在创建实例， login 这个实例后调用该方法获得 session token。

**Comment by zysoo** [comment]
瓦卡达。多谢解惑。
